version: 0.0
os: linux
files:
  - source: /        # Everything in the root of the archive is copied to /opt/codedeploy-agent/deployment-root/
    destination: /opt/codedeploy-agent/deployment-root/
    overwrite: true

