version: 0.0
os: linux
files:
  - source: /        # Everything in the root of the archive is copied to /opt/codedeploy-agent/deployment-root/
    destination: /opt/codedeploy-agent/deployment-root/
    overwrite: true

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 180
      runas: root
