version: 0.2

phases:
  install:
    commands:
      - echo "Installing Amazon Corretto (OpenJDK 11)..."
      - yum install -y java-11-amazon-corretto-devel
  build:
    commands:
      - echo "Building the project..."
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/*.jar
