version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre_build phase..."
      - echo Installing Snyk...
      - npm install -g snyk
      - echo Logging in to AWS ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 843835551300.dkr.ecr.us-east-1.amazonaws.com
     
  build:
    commands:
      - echo "Starting build phase..."
      # Build the Docker image
      - docker build --build-arg snyk_auth_token=$SNYK_AUTH_TOKEN -t 843835551300.dkr.ecr.us-east-1.amazonaws.com/lrn_demo2:latest .
      
     
      - ./snyk auth $SNYK_AUTH_TOKEN
      - ./snyk test --docker 843835551300.dkr.ecr.us-east-1.amazonaws.com/lrn_demo2:latest
      - ./snyk monitor --docker 843835551300.dkr.ecr.us-east-1.amazonaws.com/lrn_demo2:latest
   

  post_build:
    commands:
      - echo "Build phase completed."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 843835551300.dkr.ecr.us-east-1.amazonaws.com
      # Optionally push the Docker image to ECR after a successful build
      - docker push 843835551300.dkr.ecr.us-east-1.amazonaws.com/lrn_demo2:latest

artifacts:
  files:
    - target/*.jar  # Adjust if you have build artifacts to be collected
  discard-paths: yes  # Optional, to avoid including unnecessary directories


