version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11

  build:
    commands:
      - echo "Building the project..."
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/*.jar
