version: 0.2

phases:
 
  install:
    runtime-versions:
      java: openjdk11  
    commands:
      - echo "Using OpenJDK 11 runtime"
      - java -version   
      - echo "Installation phase completed."

 
  build:
    commands:
      - echo "Starting the build process..."
      - mvn clean package -DskipTests
      - echo "Build completed successfully."


artifacts:
  files:
    - target/*.jar

cache:
  paths:
    - '/root/.m2/**/*'
