version: 0.2
phases:
  pre_build:
    commands:
      - PWDUTILS=$(pwd)
      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      - chmod -R +x ./snyk
  build:
    commands:
      - echo "Starting build phase..."
      # Build the Docker image
      - docker build --build-arg snyk_auth_token=$SNYK_AUTH_TOKEN -t  <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-docker-repo:latest .

  post_build:
    commands:
      - echo "Build phase completed."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin  <aws_account_id>.dkr.ecr.<region>.amazonaws.com
      # Optionally push the Docker image to ECR after a successful build
      - docker push  <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-docker-repo:latest
