version: 0.2

phases:
  pre_build:
    commands:
      - PWDUTILS=$(pwd)
      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      - chmod -R +x ./snyk

  build:
    commands:
      - echo "Starting build phase..."
      - docker build --build-arg snyk_auth_token=$SNYK_AUTH_TOKEN -t 843835551300.dkr.ecr.us-east-1.amazonaws.com/lrn_demo2:latest .

  post_build:
    commands:
      - echo "Build phase completed."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 843835551300.dkr.ecr.us-east-1.amazonaws.com
      - docker push 843835551300.dkr.ecr.us-east-1.amazonaws.com/lrn_demo2:latest
      # Set the ECR repository URI here
      - export ECR_REPOSITORY_URI=843835551300.dkr.ecr.us-east-1.amazonaws.com/lrn_demo2
      - echo "[{\"name\":\"LRN_Demo_ECS\",\"imageUri\":\"$ECR_REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION\"}]" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
