version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo "Installing dependencies..."
      - mvn install -DskipTests

  build:
    commands:
      - echo "Building the project..."
      - mvn package -Dmaven.test.skip=true

artifacts:
  files:
    - target/*.jar
